### ISSUE TITLE
Ajout d'un style sur les .page-shortcuts .active

### ISSUE THREAD

**Issue by brrd** [edinum/nova#102]
Par exemple : 

```css
.page-shortcuts .nav-pills li.active {
  font-weight: bold;
}
```
